Ambigous grammar is difficult to parse.
expression     → literal
               | unary
               | binary
               | grouping ;

literal        → NUMBER | STRING | "true" | "false" | "nil" ;
grouping       → "(" expression ")" ;
unary          → ( "-" | "!" ) expression ;
binary         → expression operator expression ;
operator       → "==" | "!=" | "<" | "<=" | ">" | ">="
               | "+"  | "-"  | "*" | "/" ;

---------------------------------------------------------------------------
program        -> declaration* EOF ;
declaration    -> varDecl | statement ;

varDecl        -> "var" IDENTIFIER ( "=" expression )? ";" ;
statement      -> assignment | exprStatement | printStatement | block;

assignment     -> IDENTIFIER "=" expression ";" ;
exprStatement  -> expression ";" ;
printStatement -> "print" expression ";" ;
block          -> "{" declaration* "}" ;

expression     -> comma ;
comma          -> ternary ( "," ternary )* ;
ternary        -> equality ("?" expression ":" ternary )? ;
equality       -> comparison ( ( "!=" | "==" ) comparison )* ;
comparison     -> term ( ( ">" | ">=" | "<" | "<=" ) term )* ;
term           -> factor ( ( "-" | "+" ) factor )* ;
factor         -> unary ( ( "/" | "*" ) unary )* ;
unary          -> ( "!" | "-" ) unary | primary ;
primary        -> NUMBER | STRING | "true" | "false" | "nil" | "(" expression ")" | IDENTIFIER ;
